### PR TITLE
Embed embedded items without a self link into the body

### PR DESCRIPTION
**Pull request by madsmadsen**
As per the HAL spec, a self link "should" appear, but not strictly necessary. This will embed those into the body with the relType as the property name.

I'm not fan of changing the body this way, but given `ketting` is designed around everything has a unique self link, this was what I could come up with.

### CODE REVIEW

**Comment by evert** [comment]
This is a strange requirement. What is the meaning of an embedded item without a link? Why not just add this object to your body (as an author of the API)?

I don't think we're completely in the wrong ignoring embedded items without a URI. But I'm curious to hear more about your use-case

**Comment by madsmadsen** [comment]
Disclaimer, I'm not the author of the API, I'm only using it.

We add the author of a comment as an embedded item on the comment, but we do not have a "place"/endpoint for authors, so they are just plain objects without any links.

I have asked for a link to be present, because IMO it does not make, logically, sense to me that it's not there. But given that the spec does actually state that a self link is not strictly necessary I guess it's okay.

Also I added this "fix" into Ketting v4, where it was not possible to call `getEmbedded`, so it is possible that we can get the information that way around, I have not tried it, as our frontend has been created around not being able to get the embedded items that way.

**Comment by evert** [comment]
In their case I would probably suggest to:

1. Point to a uri anyway, it doesn't matter if you can't `GET` there.
2. Point to a urn like `urn:uuid:....`

Embedded items without a uri doesn't make *that* much sense I think. It would also be a pain to make the `uri` property on the `State` object optional, because it means users have to put a `if (state.uri)` guard everywhere it's used.

I can recommend a workaround though, you do some pre-processing by adding a uri/urn` on every embedded resource, this would be doable if you write your own stateFactory and register it with the mimetypes you are using. After the pre-procesing you can just call out back to the HAL one

**Comment by madsmadsen** [comment]
Good idea with a custom `stateFactory`, I'll create an internal issue for us to have a look at later on.

Currently this "fix"/"hack" works for us, so I'll just keep this in our internal build, until we get around to creating a custom `stateFactory`.

But I'll close this PR, as in general it's a bad fix/hack to a problem that does not happen is that often in the wild.

**Comment by evert** [comment]
Awesome! Just want to also say thanks for all these contributions.

**Pull request closed without merging**
