### PR TITLE
Restored parsing of minLength and maxLength for use in input and textarea fields.

### PR DESCRIPTION
**Pull request by dayre**
I've restored parsing of minLength and maxLength for use in form validation of textarea and the input types that make sense.

### CODE REVIEW

**Comment by dayre** [comment]
Sorry, my first pull request submission on github in a long while, a bit clunky.

**Comment by evert** [comment]
No worries, don't forget that your PR needs to update its copy of the `hal-types` lib, because currently it will use the old version from `package-lock.json`

**Comment by dayre** [comment]
Ah, ok, thanks i wasn't sure how those updated dependencies would get
resolved.

**Review by evert — APPROVED** [review]

**Comment by evert** [comment]
@dayre I'm going to add you as a contributor to this repo so tests run automatically as you update this PR

**Comment by dayre** [comment]
I think i've done all i can do here, the failed tests are related to some other changes ?

**Comment by evert** [comment]
Yep! that is very weird. I've recently done a lot of updates here to prepare for Node 18, and it looks like not everything took. Instead of trying to fix this here, I'm going to apply your changes to the version-7.x branch so we can release something a bit faster.

**Pull request closed without merging**
