### PR TITLE
Embedded items should only replace cache if they have the same context

### PR DESCRIPTION
**Pull request by madsmadsen**
As per the 4.1.2 in the HAL spec, an embedded item MAY be a full or partial version of a resource. So if the embedded uri is already in the cache, make sure we "own" it before replacing it.

Found this bug, when I couldn't figure out why our account view only had partial data.
And that was because we have the account as a partial embedded item, on some resources.

### CODE REVIEW

**Comment by evert** [comment]
I hate it, but I this change is also fairly contentious.

We pretty much use this as described as the [hypertext cache pattern](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-8.3), and rely on this feature with multiple deployments. I'm also aware other users take advantage of this.

In short, the use-cases is that if we have, say, a collection of articles and each article is embedded. That collection is rendered by the frontend. Now the frontend wants to get a fresh list.

If we don't update items for which we already have a cache for, it means that:

1. The frontend will see old items, OR
2. The frontend will have to follow-up with individual `GET` requests for any item in that collection.

Neither is optimal for that. You are correct however that HAL specifies that the representations might not be complete/non-authoritative.

So I'm wondering ... is there a workaround for this? Could we do both? It would be a pretty devastating BC break to lose the current behavior though...

**Comment by madsmadsen** [comment]
> So I'm wondering ... is there a workaround for this? Could we do both? It would be a pretty devastating BC break to lose the current behavior though...

After a bit of thinking and trying out different approaches, I have come up with this;
If an embedded item is already in the cache, only replace it if the `defaultContext` is the same as the new embedded item's `defaultContext`.
Also updated the `ForeverCache` to also delete the embedded items from cache if the "parent" is deleted.

Do you think that would solve the issue?

**Comment by evert** [comment]
Unfortunately it would not, at least for the cases I know of.

Example flow, think of a frontend application:

1. User requests a list, list has every item embedded.
2. User opens a single item and gets redirected to a new detail screen
3. Here, the user makes some edits. We do a `PUT` and eventually a `GET` to see the new server state.
4. User goes back to the main listing and expects an up-to-date list.

I wonder if you could just subclass ForeverCache for your purposes, and implement it there. Based on this PR this suggests that this could work for you.

I realize having all this customization is not ideal, but this will at least get you unstuck.

Note that defaultContext is also not even 100% reliable. It works for HAL, but other formats define context differently. For some formats relative links in embedded resources need to be expanded based on the `self` of that embedded resource, and not the uri of the parent document. But if HAL is your main format, this will work.

**Comment by madsmadsen** [comment]
> Example flow, think of a frontend application:
> 
> 1. User requests a list, list has every item embedded.
> 2. User opens a single item and gets redirected to a new detail screen
> 3. Here, the user makes some edits. We do a `PUT` and eventually a `GET` to see the new server state.
> 4. User goes back to the main listing and expects an up-to-date list.

If the user `PUT`'s and then `GET`'s the embedded item's self uri, that would replace the cache, as that would be a direct request, so the user should see an up-to-date list when they go back to the main list.

The context check is only done on the run when looping over embedded items, not on the main request. A direct request, like a `PUT` or `GET` on the embedded items self link would replace the cache.

Now that would of course replace the cache with a `State` which would have a different context then the embedded `State` that was already in the cache.

> I wonder if you could just subclass ForeverCache for your purposes, and implement it there. Based on this PR this suggests that this could work for you.

I added the `delete` enhancement on `ForeverCache` to solve:
> In short, the use-cases is that if we have, say, a collection of articles and each article is embedded. That collection is rendered by the frontend. Now the frontend wants to get a fresh list.

I assumed getting a fresh list implied calling `cache.delete(collectionUri)`

The defaultContext check solves the issue I had.

Also that wouldn't solve the issue I originally had, where the stream of requests includes both partially embedded item and a full representation of the same account data.

> Note that defaultContext is also not even 100% reliable. It works for HAL, but other formats define context differently. For some formats relative links in embedded resources need to be expanded based on the `self` of that embedded resource

Yeah that is an issue :/
One of the approaches I did think about, was to have a property on the `State` that would tell which request was the creator of this `State`, but I noticed `defaultContext` had what I wanted, so I just used `defaultContext`. Maybe I should go back to the approach with a `creatorContext` on `State`?

However it boils down to what the other RFC's say about embedded items, HAL does state an embedded item MAY be full, partial or even an inconsistent version of the resource, so I think it should be supported by `Ketting`.
What does the other RFC's say about embedded items?

**Comment by madsmadsen** [comment]
Skimming through the RFC's it does appear to be only HAL allowing embedded items to be partial or inconsistent, maybe the solution would be to use a different cache for `HALState` 🤔

**Comment by evert** [comment]
I'm closing this, mainly because it doesn't really have a satisfying solution at the moment :/

**Pull request closed without merging**
