### PR TITLE
Build hal embedded actions

### LINKED ISSUE #385: HalState empty actions after a followAll('content')
Hello,
I have no actions when getting each state from followAll() return.

Here an example => 
``` typescript
this.existingResource
      .follow('relation')
      .followAll('content')
      .then(resources => Promise.all(resources.map(resource => resource.get())))
      .then(states => no actions in each state)
```

When I i call `resource.get` it takes the cached state in the client.
I analyse how we build the actions of a HalState and i saw this : 
``` typescript
function parseHalForms(context: string, body: hal.HalResource): ActionInfo[] {
    if (!body._templates) return [];
    ...
}
```
But in my case the `_templates` are included in the data object (body.data), not in the body, so it returns an empty Action list.

### PR DESCRIPTION
**Pull request by hugothomas**
Hello,
This is a proposition to Fix #385

### CODE REVIEW

**Comment by evert** [comment]
This makes perfect sense! Good PR. Do you want to fix the committer on the PR at all to match your github email address?

No big deal for me, but once it's in the commit log it's forever.

**Comment by hugothomas** [comment]
No it's ok for me.
Thanks

**Comment by reda-alaoui** [comment]
Hello @evert ,

When can we expect a release including this fix? :)

**Comment by evert** [comment]
@reda-alaoui just did a release for you! thanks again for the contribution!

**Pull request merged**
